-- MySQL Script generated by MySQL Workbench
-- Mon May 15 10:54:50 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`artikelen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`artikelen` ;

CREATE TABLE IF NOT EXISTS `mydb`.`artikelen` (
  `artid` INT NOT NULL AUTO_INCREMENT,
  `artikelenomschrijving` VARCHAR(12) NOT NULL,
  `artinkoop` FLOAT NULL,
  `artverkoop` FLOAT NULL,
  `artvoorraad` INT NOT NULL,
  `artminvoorraad` INT NOT NULL,
  `artmaxvoorraad` INT NOT NULL,
  `artlocatie` INT NULL,
  `levid` INT NOT NULL,
  PRIMARY KEY (`artid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`leveranciers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`leveranciers` ;

CREATE TABLE IF NOT EXISTS `mydb`.`leveranciers` (
  `levid` INT NOT NULL,
  `levnaam` VARCHAR(15) NULL,
  `levcontact` VARCHAR(20) NULL,
  `levemail` VARCHAR(30) NULL,
  `levadres` VARCHAR(30) NULL,
  `levpostcode` VARCHAR(6) NULL,
  `levwoonplaats` VARCHAR(25) NULL,
  PRIMARY KEY (`levid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`inkooporders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`inkooporders` ;

CREATE TABLE IF NOT EXISTS `mydb`.`inkooporders` (
  `inkordid` INT NOT NULL,
  `artid` INT NOT NULL,
  `levid` INT NOT NULL,
  `inkorddatum` DATE NULL,
  `inkordbestaantal` INT NULL,
  `inkordstatus` TINYINT NULL,
  PRIMARY KEY (`inkordid`, `artid`, `levid`),
  INDEX `fk_inkooporders_artikelen_idx` (`artid` ASC) VISIBLE,
  INDEX `fk_inkooporders_leveranciers1_idx` (`levid` ASC) VISIBLE,
  UNIQUE INDEX `artikelen_artid_UNIQUE` (`artid` ASC) VISIBLE,
  UNIQUE INDEX `leveranciers_levid_UNIQUE` (`levid` ASC) VISIBLE,
  CONSTRAINT `fk_inkooporders_artikelen`
    FOREIGN KEY (`artid`)
    REFERENCES `mydb`.`artikelen` (`artid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inkooporders_leveranciers1`
    FOREIGN KEY (`levid`)
    REFERENCES `mydb`.`leveranciers` (`levid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`klanten`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`klanten` ;

CREATE TABLE IF NOT EXISTS `mydb`.`klanten` (
  `klantid` INT NOT NULL,
  `klantnaam` VARCHAR(20) NULL,
  `klantemail` VARCHAR(30) NOT NULL,
  `klantadres` VARCHAR(30) NOT NULL,
  `klantpostcode` VARCHAR(6) NULL,
  `klantwoonplaats` VARCHAR(25) NULL,
  PRIMARY KEY (`klantid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`verkooporders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`verkooporders` ;

CREATE TABLE IF NOT EXISTS `mydb`.`verkooporders` (
  `verkordid` INT NOT NULL,
  `artid` INT NOT NULL,
  `klantid` INT NOT NULL,
  `verkorddatum` DATE NULL,
  `verkordbestaantal` INT NULL,
  `verkordstatus` INT NOT NULL,
  PRIMARY KEY (`verkordid`, `artid`, `klantid`),
  INDEX `fk_verkooporders_artikelen1_idx` (`artid` ASC) VISIBLE,
  INDEX `fk_verkooporders_klanten1_idx` (`klantid` ASC) VISIBLE,
  UNIQUE INDEX `klanten_klantid_UNIQUE` (`klantid` ASC) VISIBLE,
  UNIQUE INDEX `artikelen_artid_UNIQUE` (`artid` ASC) VISIBLE,
  CONSTRAINT `fk_verkooporders_artikelen1`
    FOREIGN KEY (`artid`)
    REFERENCES `mydb`.`artikelen` (`artid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_verkooporders_klanten1`
    FOREIGN KEY (`klantid`)
    REFERENCES `mydb`.`klanten` (`klantid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
